module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'grower',
        'auth-proxy',
        'api',
        'ui',
        'auth',
        'common',
        'eslint-config',
        'prettier-config',
        'tailwind-config',
        'typescript-config',
        'deps',
        'repo',
      ],
    ],
  },
};