import type { Buyer } from "@/types/buyer.types";
import { COMPLIANCE_STATUS } from "@/utils/constants/status-constants";

export const MOCK_BUYERS: Buyer[] = [
  {
    id: "1",
    buyerName: "Acme Foods Ltd",
    country: "Ghana",
    region: "Greater Accra",
    city: "Accra",
    email: "buyers@acmefoods.com",
    phoneNumber: "+233244123456",
    status: "Active",
    createdAt: "2024-01-15T10:00:00Z",
    lastLoginAt: "2024-11-10T14:30:00Z",
    isActive: true,
    organisationId: "Acme Food Group International",
    compliance: COMPLIANCE_STATUS.lowRisk,
  },
  {
    id: "2",
    buyerName: "Global Traders Inc",
    country: "Nigeria",
    region: "Lagos",
    city: "Lagos",
    email: "contact@globaltraders.com",
    phoneNumber: "+234803456789",
    status: "Active",
    createdAt: "2024-02-20T09:00:00Z",
    lastLoginAt: "2024-11-09T11:20:00Z",
    isActive: true,
    organisationId: "Global Trading Network Ltd",
    compliance: COMPLIANCE_STATUS.lowRisk,
  },
  {
    id: "3",
    buyerName: "Farm Fresh Buyers",
    country: "Kenya",
    region: "Nairobi",
    city: "Nairobi",
    email: "info@farmfresh.co.ke",
    phoneNumber: "+254712345678",
    status: "Pending",
    createdAt: "2024-11-01T12:00:00Z",
    isActive: false,
    organisationId: "Farm Fresh Holdings",
    compliance: COMPLIANCE_STATUS.notAssigned,
  },
  {
    id: "4",
    buyerName: "Premium Agro Exports",
    country: "South Africa",
    region: "Gauteng",
    city: "Johannesburg",
    email: "sales@premiumagro.co.za",
    phoneNumber: "+27821234567",
    status: "Active",
    createdAt: "2024-03-10T08:30:00Z",
    lastLoginAt: "2024-11-11T09:15:00Z",
    isActive: true,
    organisationId: "Premium Agricultural Exports SA",
    compliance: COMPLIANCE_STATUS.prohibited,
  },
  {
    id: "5",
    buyerName: "West Africa Commodities",
    country: "Ivory Coast",
    region: "Abidjan",
    city: "Abidjan",
    email: "buyers@wactrading.ci",
    phoneNumber: "+2250708123456",
    status: "Suspended",
    createdAt: "2024-04-05T07:00:00Z",
    lastLoginAt: "2024-10-20T16:45:00Z",
    isActive: false,
    organisationId: "West African Commodities Group",
    compliance: COMPLIANCE_STATUS.highRisk,
  },
];
